version: '3'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            PGDATA: '/data/postgres'
            POSTGRES_DB: 'contactapp'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    db-test:
        image: postgres:latest
        restart: always
        environment:
            PGDATA: '/data/postgres'
            POSTGRES_DB: 'testing'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - db-test:/var/lib/postgresql/data
        ports:
            - "54320:5432"
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis:/data
volumes:
    redis:
    db:
    db-test:
